---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: clouddns-dns01-solver-svc-acct
  namespace: tap-install
spec:
  toNamespaces:
    - cert-manager
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: clouddns-dns01-solver-svc-acct
  namespace: cert-manager
spec:
  fromNamespace: tap-install