apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-overlay
  namespace: tap-install
stringData:
  custom-package-overlay.yml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "cert-manager"}})
    ---
    metadata:
      #@overlay/match missing_ok=True
      annotations:
        kapp.k14s.io/change-group: "cert-manager"
