apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: post-install-app
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting tanzu-sync-secrets"
    kapp.k14s.io/change-rule.1: "upsert after upserting cert-manager"
spec:
  serviceAccountName: tap-installer-sa
  fetch:
  - git:
      url: ssh://git@github.com/logankimmel/tap-gitops.git
      ref: origin/master
      secretRef: 
        name: sync-git
      subPath: clusters/docker-tap/cluster-config/post-install
  template:
  - ytt: {}
  deploy:
  - kapp: {}