apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: post-install-app
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting tanzu-sync"
    kapp.k14s.io/change-rule.1: "upsert after upserting tap"
    kapp.k14s.io/change-rule.2: "delete before deleting tanzu-sync"
spec:
  fetch:
  - git:
      url: ssh://git@github.com/logankimmel/tap-gitops.git
      ref: origin/master
      secretRef: 
        name: sync-git
      subPath: clusters/docker-tap/cluster-config/post-install
  template:
  - ytt: {}
  deploy:
  - kapp: {}