tap_install:
    sensitive_values:
        tap_gui:
            app_config:
                integrations:
                    github:
                        - host: ENC[AES256_GCM,data:5CkMZuuLZ7N+DQ==,iv:dEksAAx7bV38H/ysAuoLDmsr7QiSWz4NtkkHwRcuFog=,tag:c8ZCTNiEYDaJ2ea9k4vHyQ==,type:str]
                          token: ENC[AES256_GCM,data:Xq8ElykkqAw552of/r4PPuMDhTql5zqmqcJbPRUv3D115nZm7cMNsA==,iv:jlbkK86JRpX6iurbZ9oxOIPg58hshRBiuK/vdFYw4FY=,tag:VNct5Me4E/T5EkM2egVGPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dhg5g6q5vlrfk98k04d066qnc9cwe77ekt4nphkjtrv8uyfmhdgqj0m8y5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZUdHZ25RWVJOeUNYOG9N
            MWVLdU13UlkxTC96SEZCVHQ1cFg2amNCb0hRClpXRk5oamJidzFZNm1YSUMwNmhI
            NFdySVdRWURuQkRUYnk4WGZ1eUVUN0EKLS0tIFJaZ0JaUUZJTzFCeXNpdG9PRGo3
            Q0NvZ3dTRFcwTHhHekR5Smh5N1R3REUKWWQaz8JZ2IvrXXxGN9xyI8IXGe1xIWhL
            gCQrGSFaKhIkSi4LKC5mvqGaps2KBdbxfI/BrfABec8yHUqbqo7XyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-13T16:06:52Z"
    mac: ENC[AES256_GCM,data:xbWjiFJuZkVCP3TNL2GAyw0xkz13hk5WxXuudR0ZtTPv+JbYLJm7jQzBOY6z67w8wU+itCDdVDpsVUMOUw1JfcIwiBmJnygQA5AQZh3zVwgeyTDuSAwqbhHKSSrhZx6cLEK6Rsp6TnEvW18Qcq/rwshsIEqXmcXrhO0HznqLquA=,iv:+Xn7hGC3l6D1JeqxZgx95Nb585Lw+t89A9WAGEgunxs=,tag:KSLucCU8py7VZ0HO5VOpGA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
