---
tap_install:
  values:
    profile: full
    ceip_policy_disclosed: true
    excluded_packages:
      - appliveview.tanzu.vmware.com
      - backend.appliveview.tanzu.vmware.com
      - connector.appliveview.tanzu.vmware.com
      - conventions.appliveview.tanzu.vmware.com
      - cert-manager.tanzu.vmware.com
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - policy.apps.tanzu.vmware.com
      - tap-telemetry.tanzu.vmware.com
    
    contour:
      envoy:
        service:
          type: LoadBalancer
      infrastructure_provider: aws
    
    shared:
      ingress_domain: k8s.binbytes.io
    
    accelerator:
      server:
        watched_namespaces: accelerator
        service_type: ClusterIP
    
    buildservice:
      kp_default_repository: "938504343993.dkr.ecr.us-west-2.amazonaws.com/tbs"
      kp_default_repository_aws_iam_role_arn: "arn:aws:iam::938504343993:role/nodes.tkg.cloud.vmware.com"
        #  descriptor_name: "full"
        #  enable_automatic_dependency_updates: true
    
    cnrs:
      ingress:
        external:
          namespace: tanzu-system-ingress
        internal:
          namespace: tanzu-system-ingress
      domain_name: k8s.binbytes.io
      ingress_issuer: k8s-binbytes
      lite:
        enable: true
    
    supply_chain: testing_scanning
    
    ootb_supply_chain_basic:
      registry:
        server: "public.ecr.aws/n0v5c2t4"
        repository: "tap"
      gitops:
        ssh_secret: ""
    
    ootb_supply_chain_testing:
      registry:
        server: us-west1-docker.pkg.dev
        repository: lkimmel-1069/tap
      gitops:
        ssh_secret: ""
    
    ootb_supply_chain_testing_scanning:
      registry:
        #    repository: lkimmel-1069/tap
        #    server: us-west1-docker.pkg.dev
        repository: tap
        server: 938504343993.dkr.ecr.us-west-2.amazonaws.com
      gitops:
        server_address: https://github.com
        repository_owner: logankimmel
        repository_name: gitops
        commit_strategy: pull_request
        pull_request:
          server_kind: github
          commit_branch: ""
          pull_request_title: ready for review
          pull_request_body: generated by supply chain
        ssh_secret: "git-https"
    
    tap_gui:
      ingressEnabled: true
      tls:
        namespace: tap-install
        secretName: tap-gui-crt
      ingressDomain: k8s.binbytes.io
      service_type: ClusterIP
      app_config:
        app:
          baseUrl: https://tap-gui.k8s.binbytes.io
        integrations:
        catalog:
          locations:
            - type: url
              target: https://github.com/logankimmel/tap/blob/main/catalog-info.yaml
        backend:
            baseUrl: https://tap-gui.k8s.binbytes.io
            cors:
                origin: https://tap-gui.k8s.binbytes.io
        proxy:
          /metadata-store:
            target: https://metadata-store-app.metadata-store:8443/api/v1
            changeOrigin: true
            secure: false
            headers:
              X-Custom-Source: project-star
    learningcenter:
      ingressDomain: learning.k8s.binbytes.io
    
    grype:
      targetImagePullSecret: ecr
    
    metadata_store:
      ns_for_export_app_cert: "*"
      app_service_type: ClusterIP
    
    scanning:
      metadataStore:
        url: ""
    
    grype:
      targetImagePullSecret: gcr-tap-registry
    
    namespace_provisioner:
      controller: false
      aws_iam_role_arn: "arn:aws:iam::938504343993:role/nodes.tkg.cloud.vmware.com"
      additional_sources:
      - git:
          ref: origin/main
          subPath: namespace-provisioner
          url: https://github.com/logankimmel/gitops.git
        path: _ytt_lib/testingscanning
      - git:
          ref: origin/main
          url: https://github.com/logankimmel/gitops.git
          subPath: namespace-provisioner-overrides
        path: _ytt_lib/customize
