secrets:
    sops:
        registry:
            hostname: ENC[AES256_GCM,data:FRQghNA6x/O1LMDbxZ5Ota6sl65EsV2Nyw==,iv:uG6Iecl6YwsqZJpF+USPvwUZOpyvqrk09tTL+uBpaic=,tag:po1/9yfbcQH1SyH6sl/28A==,type:str]
            username: ENC[AES256_GCM,data:79QHB6rOoAdbDDRv7Ud4mwm3,iv:XT6Wd50ixHXulLIZ7zJLGe8wS6rCMLbGwRX5GIZivmQ=,tag:2jKjXbGmnLv/R+8FnDfmng==,type:str]
            password: ENC[AES256_GCM,data:uDmVf6BC8+DE+g==,iv:/cnieqEKyh1Btnyq6v5Cj7o39k3w44cLbbWmCRZjZ/Y=,tag:wtaLgOvTQNlUgE/a5xn3gg==,type:str]
        git:
            ssh:
                private_key: ""
                known_hosts: ENC[AES256_GCM,data:3Mt3OrREO0X3DQ==,iv:67twu0C6WvpoZX48LtQqa+obo8kygB7TANOa+nFOveg=,tag:sDJd6Dax6djMDxxcJnVxUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dhg5g6q5vlrfk98k04d066qnc9cwe77ekt4nphkjtrv8uyfmhdgqj0m8y5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWm9jZ1VQZWZZaCtqcXZY
            NDVUcWh3RkUveHFhVG1XU2t1RFhubnFocGdjCjlkdVhnNlFWaEd6cVpOU29mamov
            bkswSXhyc2wrSUlGbVFZWjM4THNrM00KLS0tIHJBdUhWV3R3V1p5K3NGcHBYM1Vv
            eEwrTVlwMWhmWUt3Ylg2QXM2VWZKUXMKkw0OGE2Kt8fiCvu+XKhFMZOigcTGhSVD
            7my9PdZLueDJ6ZwLvWP3Tbz5LrXiEpG+Qb1iZyHYmDxu3vscmqXutg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T05:05:15Z"
    mac: ENC[AES256_GCM,data:n6ZnWwfayOvEZ/9fdw6KJQNNhdxp5bKk4tgr3qVeL9mysSB9jRrv/VqDqMjcNB73gGTkmcvPeqvY5VBvlAF4ENVZ+jsN2feodYc3hKFZnDd2p7QIZu7Dt9+5ydMlnbTpNRnrJlFytkfMiPdIqa7RzjxEKBJJsxc8YkYuxB8tU/g=,iv:lXW6rKwrh9fH0OjkFVJkA+JBl0wV7DhXqZIo8pDkyLc=,tag:3NovLDiCy97Qu+NJVhhrvg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
